module VerifyExamples.Model.WeatherData.ToHourlyDataPoints0 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect

import Model.WeatherData exposing (..)
import Time



weatherData : ApiWeatherData
weatherData =
    { hourly = hourlyData
    , utcOffset = 7200
    }
hourlyData : ApiHourlyData
hourlyData =
    { times = [ 1667772000, 1667775600, 1667779200, 1667782800 ]
    , temperatures = [ 6.9, 6.4, 5.6, 5.4 ]
    , precipitation = [ 0, 0.1, 0.2, 0.3 ]
    }



spec0 : Test.Test
spec0 =
    Test.test "#toHourlyDataPoints: \n\n    toHourlyDataPoints weatherData\n    --> [ HourlyDataPoint (Time.millisToPosix 1667779200000) 6.9 0\n    --> , HourlyDataPoint (Time.millisToPosix 1667782800000) 6.4 0.1\n    --> , HourlyDataPoint (Time.millisToPosix 1667786400000) 5.6 0.2\n    --> , HourlyDataPoint (Time.millisToPosix 1667790000000) 5.4 0.3\n    --> ]" <|
        \() ->
            Expect.equal
                (
                toHourlyDataPoints weatherData
                )
                (
                [ HourlyDataPoint (Time.millisToPosix 1667779200000) 6.9 0
                , HourlyDataPoint (Time.millisToPosix 1667782800000) 6.4 0.1
                , HourlyDataPoint (Time.millisToPosix 1667786400000) 5.6 0.2
                , HourlyDataPoint (Time.millisToPosix 1667790000000) 5.4 0.3
                ]
                )