module VerifyExamples.Util.GroupBy0 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect

import Util exposing (..)







spec0 : Test.Test
spec0 =
    Test.test "#groupBy: \n\n    groupBy identity []\n    --> []" <|
        \() ->
            Expect.equal
                (
                groupBy identity []
                )
                (
                []
                )