module VerifyExamples.Util.GroupBy2 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect

import Util exposing (..)







spec2 : Test.Test
spec2 =
    Test.test "#groupBy: \n\n    groupBy .x [ { x = 1 } ]\n    --> [(1, [{x = 1}])]" <|
        \() ->
            Expect.equal
                (
                groupBy .x [ { x = 1 } ]
                )
                (
                [(1, [{x = 1}])]
                )