module VerifyExamples.Util.MaybeToList1 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect

import Util exposing (..)







spec1 : Test.Test
spec1 =
    Test.test "#maybeToList: \n\n    maybeToList (Just 1)\n    --> [1]" <|
        \() ->
            Expect.equal
                (
                maybeToList (Just 1)
                )
                (
                [1]
                )