module VerifyExamples.Util.ZipFilter0 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect

import Util exposing (..)







spec0 : Test.Test
spec0 =
    Test.test "#zipFilter: \n\n    zipFilter [ True, False, True, False ] [ 1, 2, 3, 4 ]\n    --> [1, 3]" <|
        \() ->
            Expect.equal
                (
                zipFilter [ True, False, True, False ] [ 1, 2, 3, 4 ]
                )
                (
                [1, 3]
                )