module VerifyExamples.Util.ZipFilter2 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect

import Util exposing (..)







spec2 : Test.Test
spec2 =
    Test.test "#zipFilter: \n\n    zipFilter [ True, True ] [ 1, 2 ]\n    --> [1, 2]" <|
        \() ->
            Expect.equal
                (
                zipFilter [ True, True ] [ 1, 2 ]
                )
                (
                [1, 2]
                )