module VerifyExamples.Model.WeatherItems.AllSelected0 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect

import Model.WeatherItems exposing (..)







spec0 : Test.Test
spec0 =
    Test.test "#allSelected: \n\n    List.all (\\i -> isItemSelected i allSelected) weatherItems\n    --> True" <|
        \() ->
            Expect.equal
                (
                List.all (\i -> isItemSelected i allSelected) weatherItems
                )
                (
                True
                )