module VerifyExamples.Model.WeatherItems.IsItemSelected0 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect

import Model.WeatherItems exposing (..)







spec0 : Test.Test
spec0 =
    Test.test "#isItemSelected: \n\n    isItemSelected Temperature allSelected\n    --> True" <|
        \() ->
            Expect.equal
                (
                isItemSelected Temperature allSelected
                )
                (
                True
                )