module VerifyExamples.Model.WeatherItems.Set0 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect

import Model.WeatherItems exposing (..)







spec0 : Test.Test
spec0 =
    Test.test "#set: \n\n    allSelected |> set Precipitation False |> isItemSelected Temperature\n    --> True" <|
        \() ->
            Expect.equal
                (
                allSelected |> set Precipitation False |> isItemSelected Temperature
                )
                (
                True
                )