module VerifyExamples.Model.WeatherItems.Set1 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect

import Model.WeatherItems exposing (..)







spec1 : Test.Test
spec1 =
    Test.test "#set: \n\n    allSelected |> set Temperature False |> isItemSelected Temperature\n    --> False" <|
        \() ->
            Expect.equal
                (
                allSelected |> set Temperature False |> isItemSelected Temperature
                )
                (
                False
                )